### ISSUE TITLE
Issue: Linking Issue

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [farling42/fvtt-export-markdown#2]
Gday Farling, 

I took this for a spin tonight. The format looks lovely and working really quite well. 

I have noticed an issue with some of the linking though. 
![image](https://github.com/farling42/fvtt-export-markdown/assets/96321415/e410c6da-eda2-44a2-bbcf-30ff70d6a397)

Here is an example where the link includes an expected folder structure. The link that the export is providing though is not matching the folder structure of the output and thus the link is broken. 

The link in question is:
[[Abomination Vaults/Adventure Toolbox/The Roseguard|Roseguard]]

But the note is at the following:
F:\Obsidian\PF2e New\**Abomination Vaults\Adventure Toolbox\Abomination Vaults\Adventure Toolbox**\The Roseguard

Looks like it is duplicating part of the folder structure. 

![image](https://github.com/farling42/fvtt-export-markdown/assets/96321415/295b4f8a-4e60-47d9-ad82-e2dbf0e3427a)

Josh

**Comment by farling42** [comment]
Folders have been removed from links.

But since I was fixing links, I've added the ability to include linking to sections within a note.

All available in 0.3.0
